project:
  type: website

website:
  title: "Quorto"
  
  navbar:
    left:
      - href: index.qmd
        text: Home
      - data-class.qmd
      - about.qmd
    

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true



